"use client";
import { CheckCircle2, Eye, EyeOff, Loader2, LockKeyhole } from "lucide-react";
import { FormEvent, useState } from "react";
import { createSupabaseBrowser } from "@/src/database/supabase/browser";

export function ResetPasswordView(){
 const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [visible,setVisible]=useState(false);const [loading,setLoading]=useState(false);const [message,setMessage]=useState<{error?:boolean;text:string}|null>(null);
 const submit=async(event:FormEvent)=>{event.preventDefault();if(password!==confirm){setMessage({error:true,text:"Las contraseñas no coinciden."});return}setLoading(true);const supabase=createSupabaseBrowser();if(!supabase){setMessage({error:true,text:"La conexión de acceso no está configurada."});setLoading(false);return}const {error}=await supabase.auth.updateUser({password});setLoading(false);setMessage(error?{error:true,text:error.message}:{text:"Contraseña actualizada correctamente."})};
  return <main className="auth-simple"><section className="auth-card"><div className="auth-mobile-brand visible"><span className="auth-mark">AM</span><strong>Area Mail</strong></div><header><span className="eyebrow">Seguridad</span><h2>Crea una nueva contraseña</h2><p>Utiliza al menos doce caracteres y evita reutilizar una contraseña anterior.</p></header><form className="auth-form" onSubmit={submit}><div className="auth-field"><label htmlFor="reset-pwd">Nueva contraseña</label><div className="auth-input"><LockKeyhole size={16}/><input id="reset-pwd" type={visible?"text":"password"} minLength={12} maxLength={128} required value={password} onChange={e=>setPassword(e.target.value)}/><button type="button" onClick={()=>setVisible(v=>!v)} aria-label={visible?"Ocultar contraseña":"Mostrar contraseña"}>{visible?<EyeOff size={16}/>:<Eye size={16}/>}</button></div></div><div className="auth-field"><label htmlFor="reset-confirm-pwd">Confirmar contraseña</label><div className="auth-input"><LockKeyhole size={16}/><input id="reset-confirm-pwd" type={visible?"text":"password"} minLength={12} maxLength={128} required value={confirm} onChange={e=>setConfirm(e.target.value)}/></div></div>{message&&<div className={`auth-feedback ${message.error?"error":"success"}`} role="status">{!message.error&&<CheckCircle2 size={15}/>} {message.text}</div>}<button className="btn primary auth-submit" disabled={loading}>{loading&&<Loader2 className="spin" size={16}/>}Guardar contraseña</button>{message&&!message.error&&<a className="btn" href="/login">Volver al acceso</a>}</form></section></main>;
}
