"use client";

import { CalendarDays, CircleAlert, CircleCheck, RefreshCw, Send } from "lucide-react";
import { useEffect, useMemo, useState } from "react";

type SentEmailItem = { id: string; to: string; subject: string; from: string; date: string; status: string; errorMessage?: string };
export function SentEmailsHistory() {
  const [items,setItems]=useState<SentEmailItem[]>([]); const [loading,setLoading]=useState(true); const [fromDate,setFromDate]=useState(""); const [toDate,setToDate]=useState(""); const [statusFilter,setStatusFilter]=useState("all"); const [query,setQuery]=useState(""); const [checking,setChecking]=useState<string|null>(null);
  const load=async()=>{setLoading(true);try{const response=await fetch("/api/resend/emails",{cache:"no-store"});const payload=await response.json();if(!response.ok)throw new Error();setItems(payload.emails??[])}finally{setLoading(false)}};
  useEffect(()=>{const timer=window.setTimeout(()=>{void load()},0);return()=>window.clearTimeout(timer)},[]);
  const rows=useMemo(()=>items.filter(item=>{const date=item.date?.slice(0,10)??"";return (!fromDate||date>=fromDate)&&(!toDate||date<=toDate)&&(statusFilter==="all"||item.status===statusFilter)&&(!query||`${item.to} ${item.subject} ${item.id}`.toLowerCase().includes(query.toLowerCase()))}),[items,fromDate,toDate,statusFilter,query]);
  const refresh=async(id:string)=>{setChecking(id);try{const response=await fetch(`/api/resend/emails/${id}`);const payload=await response.json();if(response.ok&&payload.email)setItems(current=>current.map(item=>item.id===id?{...item,status:payload.email.last_event??payload.email.status??item.status}:item))}finally{setChecking(null)}};
  if(loading)return <div className="activity-skeleton" aria-label="Cargando historial"><span/><span/><span/></div>;
  return <div className="email-history"><div className="card email-history-toolbar"><div className="email-filter"><CalendarDays size={14}/><input aria-label="Desde" type="date" value={fromDate} onChange={e=>setFromDate(e.target.value)}/><span>—</span><input aria-label="Hasta" type="date" value={toDate} onChange={e=>setToDate(e.target.value)}/></div><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">Todos los estados</option><option value="sent">Enviado</option><option value="delivered">Entregado</option><option value="bounced">Rebotado</option><option value="failed">Fallido</option></select><input className="email-search" placeholder="Buscar correo o asunto" value={query} onChange={e=>setQuery(e.target.value)}/><button className="btn" onClick={()=>void load()}><RefreshCw size={14}/>Actualizar</button></div><p className="email-history-count">{rows.length} de {items.length} correos registrados en Supabase</p>{rows.length?<div className="card table-wrap responsive-table"><table><thead><tr><th>Fecha</th><th>Destinatario</th><th>Asunto</th><th>Remitente</th><th>Estado</th><th/></tr></thead><tbody>{rows.map(item=>{const state=item.status.replace(/^email\./,"");const Icon=state==="delivered"?CircleCheck:state==="bounced"||state==="failed"?CircleAlert:Send;return <tr key={item.id}><td data-label="Fecha">{new Date(item.date).toLocaleString("es-PE",{dateStyle:"medium",timeStyle:"short"})}</td><td data-label="Destinatario"><strong>{item.to}</strong></td><td data-label="Asunto">{item.subject}</td><td data-label="Remitente">{item.from}</td><td data-label="Estado"><span className={`email-state ${state}`}><Icon size={13}/>{state}</span></td><td data-label="Acción"><button className="btn" disabled={checking===item.id} onClick={()=>void refresh(item.id)}>{checking===item.id?<RefreshCw className="spin" size={13}/>:<RefreshCw size={13}/>}Verificar</button></td></tr>})}</tbody></table></div>:<div className="card compact-empty"><span>No hay correos persistidos para estos filtros.</span></div>}</div>;
}
