"use client";
import { Building2, ChevronDown, Loader2, Plus } from "lucide-react";
import { useState } from "react";

type Form = { domain: string; name: string; senderEmail: string; senderName: string; businessType: string; description: string };
const initial: Form = { domain:"", name:"", senderEmail:"", senderName:"", businessType:"", description:"" };
export function SiteCreateForm({ onCancel }: { onCancel?: () => void } = {}) {
  const [form,setForm]=useState(initial); const [saving,setSaving]=useState(false); const [error,setError]=useState(""); const [attempted,setAttempted]=useState(false);
  const domainValid=/^(?:https?:\/\/)?(?:[a-z0-9-]+\.)+[a-z]{2,}(?:\/.*)?$/i.test(form.domain.trim());
  const emailValid=!form.senderEmail.trim() || /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(form.senderEmail.trim());
  const update=(key:keyof Form,value:string)=>{setForm(current=>({...current,[key]:value}));setError("")};
  const submit=async()=>{setAttempted(true);if(!domainValid||!emailValid)return;setSaving(true);setError("");try{const response=await fetch("/api/sites",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(form)});const payload=await response.json();if(!response.ok)throw new Error(payload.error??"No se pudo crear el sitio.");window.location.assign(`/sites/${payload.site.id}`)}catch(cause){setError(cause instanceof Error?cause.message:"No se pudo crear el sitio.")}finally{setSaving(false)}};
  return <section className="card site-onboarding"><div className="site-onboarding-intro"><span className="onboarding-icon"><Building2 size={18}/></span><div><span className="eyebrow">Nueva marca</span><h2>Conecta un dominio</h2><p>Crearemos la identidad y el remitente sugerido automáticamente. Podrás ajustar los detalles después.</p></div></div><div className="site-quick-create"><label className="field"><span>Dominio principal</span><input autoComplete="url" value={form.domain} aria-invalid={attempted&&!domainValid} aria-describedby="site-domain-error" onChange={e=>update("domain",e.target.value)} placeholder="tudominio.com" required/>{attempted&&!domainValid?<small className="field-error" id="site-domain-error">Escribe un dominio válido, por ejemplo empresa.com.</small>:<small>Ejemplo: areaprime.com.pe</small>}</label><button className="btn primary" disabled={saving} onClick={()=>void submit()}>{saving?<Loader2 className="spin" size={15}/>:<Plus size={15}/>}Crear marca</button></div><details className="site-advanced"><summary><ChevronDown size={15}/>Personalizar datos ahora <span>Opcional</span></summary><div className="site-onboarding-grid"><label className="field"><span>Nombre de la marca</span><input value={form.name} onChange={e=>update("name",e.target.value)} placeholder="Se genera desde el dominio"/></label><label className="field"><span>Correo remitente</span><input type="email" value={form.senderEmail} aria-invalid={attempted&&!emailValid} aria-describedby="site-email-error" onChange={e=>update("senderEmail",e.target.value)} placeholder="novedades@tudominio.com"/>{attempted&&!emailValid&&<small className="field-error" id="site-email-error">Revisa el formato del correo remitente.</small>}</label><label className="field"><span>Nombre del remitente</span><input value={form.senderName} onChange={e=>update("senderName",e.target.value)} placeholder="Se genera desde el dominio"/></label><label className="field"><span>Tipo de negocio</span><input value={form.businessType} onChange={e=>update("businessType",e.target.value)} placeholder="Ej. Inmobiliaria"/></label><label className="field full"><span>Descripción</span><input value={form.description} onChange={e=>update("description",e.target.value)} placeholder="Una descripción breve de la marca."/></label></div></details>{error&&<p className="notice error" role="alert">{error}</p>}{onCancel && <footer className="site-create-cancel"><button className="btn" type="button" onClick={onCancel}>Cancelar</button></footer>}</section>;
}
